sudo: required

language: cpp

os:
  - linux
  - osx

compiler:
  - clang

services:
    - docker

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-ubuntu.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-osx.sh; fi
